### ตรวจสอบว่ารันเซิร์ฟเวอร์อยู่หรือไม่
GET http://localhost:8081/

### เปิด Chromium ในโหมดเต็มจอ
POST http://localhost:8081/command?cmd=open_chrome

### ย้ายเมาส์ไปที่ตำแหน่ง (500, 400)
POST http://localhost:8081/command?cmd=move_mouse&x=500&y=400

### คลิกเมาส์
POST http://localhost:8081/command?cmd=click_mouse

### ถ่ายภาพหน้าจอเต็มจอ
POST http://localhost:8081/command?cmd=take_screenshot&type=fullscreen

### ถ่ายภาพหน้าจอรอบๆ เมาส์ (ยัง bugs ถ้าเลื่อนไปข้างๆ เกิน limit ค่อยแก้)
POST http://localhost:8081/command?cmd=take_screenshot&type=mouse
